"""Curated catalog of Indian historical and administrative geographic transitions."""

from typing import List, Dict, Optional
from app.temporal.models import HistoricalNameRecord, TemporalRelationshipType, TemporalEntityType

HISTORICAL_RECORDS: List[HistoricalNameRecord] = [
    # --- Major Metros & Cities ---
    HistoricalNameRecord(
        current_name="Mumbai",
        historical_name="Bombay",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1995,
        effective_date="1995-11-01",
        valid_from="1534-01-01",
        valid_to="1995-11-01",
        state="Maharashtra",
        district="Mumbai City",
        authority_note="Renamed by Maharashtra State Legislature / Central Government notification 1995",
        synonyms=["Bambai", "Mumbadevi"]
    ),
    HistoricalNameRecord(
        current_name="Pune",
        historical_name="Poona",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1978,
        effective_date="1978-01-01",
        valid_from="1818-01-01",
        valid_to="1978-01-01",
        state="Maharashtra",
        district="Pune",
        authority_note="Restored from British anglicized spelling 'Poona' to 'Pune' in 1978",
        synonyms=["Punya", "Punyavishaya"]
    ),
    HistoricalNameRecord(
        current_name="Kolkata",
        historical_name="Calcutta",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2001,
        effective_date="2001-01-01",
        valid_from="1690-08-24",
        valid_to="2001-01-01",
        state="West Bengal",
        district="Kolkata",
        authority_note="West Bengal Government notification 2001",
        synonyms=["Kalikata", "Colcutta"]
    ),
    HistoricalNameRecord(
        current_name="Chennai",
        historical_name="Madras",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1996,
        effective_date="1996-08-01",
        valid_from="1639-08-22",
        valid_to="1996-08-01",
        state="Tamil Nadu",
        district="Chennai",
        authority_note="Tamil Nadu Government notification 1996",
        synonyms=["Madraspatnam", "Chennapatnam"]
    ),
    HistoricalNameRecord(
        current_name="Bengaluru",
        historical_name="Bangalore",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_from="1831-01-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Bengaluru Urban",
        authority_note="Ministry of Home Affairs clearance & Karnataka notification 2014",
        synonyms=["Benda-kalooru"]
    ),
    HistoricalNameRecord(
        current_name="Mysuru",
        historical_name="Mysore",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Mysuru",
        authority_note="Karnataka City Renaming notification 2014"
    ),
    HistoricalNameRecord(
        current_name="Mangaluru",
        historical_name="Mangalore",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Dakshina Kannada",
        authority_note="Karnataka City Renaming notification 2014"
    ),
    HistoricalNameRecord(
        current_name="Belagavi",
        historical_name="Belgaum",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Belagavi",
        authority_note="Karnataka City Renaming notification 2014"
    ),
    HistoricalNameRecord(
        current_name="Hubballi",
        historical_name="Hubli",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Dharwad",
        authority_note="Karnataka City Renaming notification 2014"
    ),
    HistoricalNameRecord(
        current_name="Kalaburagi",
        historical_name="Gulbarga",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Kalaburagi",
        authority_note="Karnataka City Renaming notification 2014"
    ),
    HistoricalNameRecord(
        current_name="Ballari",
        historical_name="Bellary",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Ballari",
        authority_note="Karnataka City Renaming notification 2014"
    ),
    HistoricalNameRecord(
        current_name="Vijayapura",
        historical_name="Bijapur",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Vijayapura",
        authority_note="Karnataka City Renaming notification 2014"
    ),
    HistoricalNameRecord(
        current_name="Shivamogga",
        historical_name="Shimoga",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=2014,
        effective_date="2014-11-01",
        valid_to="2014-11-01",
        state="Karnataka",
        district="Shivamogga",
        authority_note="Karnataka City Renaming notification 2014"
    ),
    HistoricalNameRecord(
        current_name="Kochi",
        historical_name="Cochin",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1996,
        effective_date="1996-01-01",
        valid_to="1996-01-01",
        state="Kerala",
        district="Ernakulam",
        authority_note="Kerala State notification 1996"
    ),
    HistoricalNameRecord(
        current_name="Thiruvananthapuram",
        historical_name="Trivandrum",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1991,
        effective_date="1991-01-01",
        valid_to="1991-01-01",
        state="Kerala",
        district="Thiruvananthapuram",
        authority_note="Kerala State notification 1991"
    ),
    HistoricalNameRecord(
        current_name="Kozhikode",
        historical_name="Calicut",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1990,
        effective_date="1990-01-01",
        valid_to="1990-01-01",
        state="Kerala",
        district="Kozhikode",
        authority_note="Kerala State notification 1990"
    ),
    HistoricalNameRecord(
        current_name="Kollam",
        historical_name="Quilon",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1990,
        effective_date="1990-01-01",
        valid_to="1990-01-01",
        state="Kerala",
        district="Kollam",
        authority_note="Kerala State notification 1990"
    ),
    HistoricalNameRecord(
        current_name="Alappuzha",
        historical_name="Alleppey",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1990,
        effective_date="1990-01-01",
        valid_to="1990-01-01",
        state="Kerala",
        district="Alappuzha",
        authority_note="Kerala State notification 1990"
    ),
    HistoricalNameRecord(
        current_name="Kannur",
        historical_name="Cannanore",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1990,
        effective_date="1990-01-01",
        valid_to="1990-01-01",
        state="Kerala",
        district="Kannur",
        authority_note="Kerala State notification 1990"
    ),
    HistoricalNameRecord(
        current_name="Palakkad",
        historical_name="Palghat",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1990,
        effective_date="1990-01-01",
        valid_to="1990-01-01",
        state="Kerala",
        district="Palakkad",
        authority_note="Kerala State notification 1990"
    ),
    HistoricalNameRecord(
        current_name="Thrissur",
        historical_name="Trichur",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1990,
        effective_date="1990-01-01",
        valid_to="1990-01-01",
        state="Kerala",
        district="Thrissur",
        authority_note="Kerala State notification 1990"
    ),
    HistoricalNameRecord(
        current_name="Thalassery",
        historical_name="Tellicherry",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1990,
        effective_date="1990-01-01",
        valid_to="1990-01-01",
        state="Kerala",
        district="Kannur",
        authority_note="Kerala State notification 1990"
    ),
    HistoricalNameRecord(
        current_name="Vadodara",
        historical_name="Baroda",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1974,
        effective_date="1974-01-01",
        valid_to="1974-01-01",
        state="Gujarat",
        district="Vadodara",
        authority_note="Gujarat State notification 1974"
    ),
    HistoricalNameRecord(
        current_name="Visakhapatnam",
        historical_name="Vizagapatam",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1987,
        effective_date="1987-01-01",
        valid_to="1987-01-01",
        state="Andhra Pradesh",
        district="Visakhapatnam",
        authority_note="Andhra Pradesh State notification 1987",
        synonyms=["Waltair", "Vizag"]
    ),
    HistoricalNameRecord(
        current_name="Shimla",
        historical_name="Simla",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1974,
        effective_date="1974-01-01",
        valid_to="1974-01-01",
        state="Himachal Pradesh",
        district="Shimla",
        authority_note="Himachal Pradesh State notification 1974"
    ),
    HistoricalNameRecord(
        current_name="Guwahati",
        historical_name="Gauhati",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1983,
        effective_date="1983-01-01",
        valid_to="1983-01-01",
        state="Assam",
        district="Kamrup Metropolitan",
        authority_note="Assam State notification 1983"
    ),
    HistoricalNameRecord(
        current_name="Varanasi",
        historical_name="Benares",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1956,
        effective_date="1956-05-24",
        valid_to="1956-05-24",
        state="Uttar Pradesh",
        district="Varanasi",
        authority_note="Uttar Pradesh State notification 1956",
        synonyms=["Banaras", "Kashi"]
    ),
    HistoricalNameRecord(
        current_name="Kanpur",
        historical_name="Cawnpore",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.CITY,
        effective_year=1948,
        effective_date="1948-01-01",
        valid_to="1948-01-01",
        state="Uttar Pradesh",
        district="Kanpur Nagar",
        authority_note="Uttar Pradesh notification 1948"
    ),
    HistoricalNameRecord(
        current_name="Prayagraj",
        historical_name="Allahabad",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.DISTRICT,
        effective_year=2018,
        effective_date="2018-10-16",
        valid_from="1575-01-01",
        valid_to="2018-10-16",
        state="Uttar Pradesh",
        district="Prayagraj",
        authority_note="UP Government notification dated 16 Oct 2018",
        synonyms=["Illahabad"]
    ),
    HistoricalNameRecord(
        current_name="Ayodhya",
        historical_name="Faizabad",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.DISTRICT,
        effective_year=2018,
        effective_date="2018-11-13",
        valid_to="2018-11-13",
        state="Uttar Pradesh",
        district="Ayodhya",
        authority_note="UP Government notification dated 13 Nov 2018"
    ),
    HistoricalNameRecord(
        current_name="Gurugram",
        historical_name="Gurgaon",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.DISTRICT,
        effective_year=2016,
        effective_date="2016-04-12",
        valid_to="2016-04-12",
        state="Haryana",
        district="Gurugram",
        authority_note="Haryana Government notification dated 12 Apr 2016"
    ),
    HistoricalNameRecord(
        current_name="Nuh",
        historical_name="Mewat",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.DISTRICT,
        effective_year=2016,
        effective_date="2016-04-12",
        valid_to="2016-04-12",
        state="Haryana",
        district="Nuh",
        authority_note="Haryana Government notification dated 12 Apr 2016"
    ),
    HistoricalNameRecord(
        current_name="Chhatrapati Sambhajinagar",
        historical_name="Aurangabad",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.DISTRICT,
        effective_year=2022,
        effective_date="2022-07-16",
        valid_to="2022-07-16",
        state="Maharashtra",
        district="Chhatrapati Sambhajinagar",
        authority_note="Maharashtra Cabinet decision 2022 / MHA clearance 2023",
        synonyms=["Sambhajinagar", "Kharki"]
    ),
    HistoricalNameRecord(
        current_name="Dharashiv",
        historical_name="Osmanabad",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.DISTRICT,
        effective_year=2022,
        effective_date="2022-07-16",
        valid_to="2022-07-16",
        state="Maharashtra",
        district="Dharashiv",
        authority_note="Maharashtra Cabinet decision 2022 / MHA clearance 2023"
    ),
    HistoricalNameRecord(
        current_name="Ahilyanagar",
        historical_name="Ahmednagar",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.DISTRICT,
        effective_year=2023,
        effective_date="2023-05-31",
        valid_to="2023-05-31",
        state="Maharashtra",
        district="Ahilyanagar",
        authority_note="Maharashtra Government announcement 2023"
    ),
    HistoricalNameRecord(
        current_name="Narmadapuram",
        historical_name="Hoshangabad",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.DISTRICT,
        effective_year=2022,
        effective_date="2022-02-07",
        valid_to="2022-02-07",
        state="Madhya Pradesh",
        district="Narmadapuram",
        authority_note="MP Government notification 2022"
    ),
    # --- States & Union Territories ---
    HistoricalNameRecord(
        current_name="Odisha",
        historical_name="Orissa",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.STATE,
        effective_year=2011,
        effective_date="2011-11-01",
        valid_to="2011-11-01",
        authority_note="Constitution (113th Amendment) Act, 2011"
    ),
    HistoricalNameRecord(
        current_name="Uttarakhand",
        historical_name="Uttaranchal",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.STATE,
        effective_year=2007,
        effective_date="2007-01-01",
        valid_to="2007-01-01",
        authority_note="Uttaranchal (Alteration of Name) Act, 2006"
    ),
    HistoricalNameRecord(
        current_name="Puducherry",
        historical_name="Pondicherry",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.STATE,
        effective_year=2006,
        effective_date="2006-10-01",
        valid_to="2006-10-01",
        authority_note="Pondicherry (Alteration of Name) Act, 2006"
    ),
    HistoricalNameRecord(
        current_name="Tamil Nadu",
        historical_name="Madras State",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.STATE,
        effective_year=1969,
        effective_date="1969-01-14",
        valid_to="1969-01-14",
        authority_note="Madras State (Alteration of Name) Act, 1968"
    ),
    HistoricalNameRecord(
        current_name="Karnataka",
        historical_name="Mysore State",
        relationship=TemporalRelationshipType.RENAMED_TO,
        entity_type=TemporalEntityType.STATE,
        effective_year=1973,
        effective_date="1973-11-01",
        valid_to="1973-11-01",
        authority_note="Mysore State (Alteration of Name) Act, 1973"
    ),
    HistoricalNameRecord(
        current_name="Telangana",
        historical_name="Andhra Pradesh",
        relationship=TemporalRelationshipType.BIFURCATED_INTO,
        entity_type=TemporalEntityType.STATE,
        effective_year=2014,
        effective_date="2014-06-02",
        authority_note="Andhra Pradesh Reorganisation Act, 2014"
    ),
    HistoricalNameRecord(
        current_name="Ladakh",
        historical_name="Jammu and Kashmir",
        relationship=TemporalRelationshipType.BIFURCATED_INTO,
        entity_type=TemporalEntityType.STATE,
        effective_year=2019,
        effective_date="2019-10-31",
        authority_note="Jammu and Kashmir Reorganisation Act, 2019"
    ),
    HistoricalNameRecord(
        current_name="Jharkhand",
        historical_name="Bihar",
        relationship=TemporalRelationshipType.BIFURCATED_INTO,
        entity_type=TemporalEntityType.STATE,
        effective_year=2000,
        effective_date="2000-11-15",
        authority_note="Bihar Reorganisation Act, 2000"
    ),
    HistoricalNameRecord(
        current_name="Chhattisgarh",
        historical_name="Madhya Pradesh",
        relationship=TemporalRelationshipType.BIFURCATED_INTO,
        entity_type=TemporalEntityType.STATE,
        effective_year=2000,
        effective_date="2000-11-01",
        authority_note="Madhya Pradesh Reorganisation Act, 2000"
    ),
]


def get_all_temporal_records() -> List[HistoricalNameRecord]:
    return HISTORICAL_RECORDS
