"""Curated landmark catalog covering major Indian urban centers and key points of interest."""

from typing import List
from app.landmarks.models import LandmarkEntity, LandmarkCategory

LANDMARK_CATALOG: List[LandmarkEntity] = [
    # --- Pune Landmarks ---
    LandmarkEntity(
        id="lm_pune_shaniwar_wada",
        name="Shaniwar Wada",
        category=LandmarkCategory.HERITAGE,
        locality="Shaniwar Peth",
        taluka="Haveli",
        district="Pune",
        state="Maharashtra",
        pincode="411030",
        latitude=18.5196,
        longitude=73.8553,
        aliases=["Shaniwarwada", "Shanivar Wada", "शनिवार वाडा"],
        keywords=["fort", "heritage", "peth"]
    ),
    LandmarkEntity(
        id="lm_pune_railway_station",
        name="Pune Railway Station",
        category=LandmarkCategory.TRANSIT,
        locality="Camp",
        taluka="Haveli",
        district="Pune",
        state="Maharashtra",
        pincode="411001",
        latitude=18.5284,
        longitude=73.8744,
        aliases=["Pune Junction", "Pune Station", "पुणे स्टेशन"],
        keywords=["station", "railway", "junction"]
    ),
    LandmarkEntity(
        id="lm_pune_hinjawadi_it_park",
        name="Rajiv Gandhi Infotech Park Hinjawadi",
        category=LandmarkCategory.TECH_PARK,
        locality="Hinjawadi",
        taluka="Mulshi",
        district="Pune",
        state="Maharashtra",
        pincode="411057",
        latitude=18.5913,
        longitude=73.7389,
        aliases=["Hinjewadi IT Park", "Hinjawadi Phase 1", "Hinjawadi Phase 2", "Hinjawadi Phase 3", "Hinjawadi"],
        keywords=["it park", "tech park", "infotech"]
    ),
    LandmarkEntity(
        id="lm_pune_sppu",
        name="Savitribai Phule Pune University",
        category=LandmarkCategory.EDUCATION,
        locality="Ganeshkhind",
        taluka="Haveli",
        district="Pune",
        state="Maharashtra",
        pincode="411007",
        latitude=18.5529,
        longitude=73.8262,
        aliases=["Pune University", "SPPU", "पुणे विद्यापीठ"],
        keywords=["university", "campus", "ganeshkhind"]
    ),
    LandmarkEntity(
        id="lm_pune_magarpatta_cybercity",
        name="Magarpatta Cybercity",
        category=LandmarkCategory.TECH_PARK,
        locality="Hadapsar",
        taluka="Haveli",
        district="Pune",
        state="Maharashtra",
        pincode="411028",
        latitude=18.5167,
        longitude=73.9272,
        aliases=["Magarpatta City", "Magarpatta"],
        keywords=["cybercity", "hadapsar", "magarpatta"]
    ),
    LandmarkEntity(
        id="lm_pune_eon_free_zone",
        name="EON Free Zone Kharadi",
        category=LandmarkCategory.TECH_PARK,
        locality="Kharadi",
        taluka="Haveli",
        district="Pune",
        state="Maharashtra",
        pincode="411014",
        latitude=18.5514,
        longitude=73.9405,
        aliases=["EON IT Park", "EON Freezone", "Kharadi IT Park"],
        keywords=["eon", "kharadi", "tech park"]
    ),
    LandmarkEntity(
        id="lm_pune_ruby_hall_clinic",
        name="Ruby Hall Clinic",
        category=LandmarkCategory.HEALTHCARE,
        locality="Sassoon Road",
        taluka="Haveli",
        district="Pune",
        state="Maharashtra",
        pincode="411001",
        latitude=18.5302,
        longitude=73.8761,
        aliases=["Ruby Hall Hospital", "Ruby Hall"],
        keywords=["hospital", "clinic", "healthcare"]
    ),
    LandmarkEntity(
        id="lm_pune_dagdusheth_temple",
        name="Shrimant Dagdusheth Halwai Ganpati Mandir",
        category=LandmarkCategory.WORSHIP,
        locality="Budhwar Peth",
        taluka="Haveli",
        district="Pune",
        state="Maharashtra",
        pincode="411002",
        latitude=18.5165,
        longitude=73.8560,
        aliases=["Dagdusheth Ganpati", "Dagdusheth Temple", "दगडूशेठ गणपती"],
        keywords=["temple", "mandir", "ganpati"]
    ),

    # --- Mumbai Landmarks ---
    LandmarkEntity(
        id="lm_mumbai_gateway_of_india",
        name="Gateway of India",
        category=LandmarkCategory.HERITAGE,
        locality="Colaba",
        taluka="Mumbai City",
        district="Mumbai City",
        state="Maharashtra",
        pincode="400001",
        latitude=18.9220,
        longitude=72.8347,
        aliases=["Gateway", "गेटवे ऑफ इंडिया"],
        keywords=["monument", "colaba", "sea"]
    ),
    LandmarkEntity(
        id="lm_mumbai_csmt",
        name="Chhatrapati Shivaji Maharaj Terminus",
        category=LandmarkCategory.TRANSIT,
        locality="Fort",
        taluka="Mumbai City",
        district="Mumbai City",
        state="Maharashtra",
        pincode="400001",
        latitude=18.9401,
        longitude=72.8354,
        aliases=["CSMT", "VT Station", "Victoria Terminus", "CSMT Station"],
        keywords=["terminus", "station", "railway"]
    ),
    LandmarkEntity(
        id="lm_mumbai_iit_bombay",
        name="IIT Bombay",
        category=LandmarkCategory.EDUCATION,
        locality="Powai",
        taluka="Kurla",
        district="Mumbai Suburban",
        state="Maharashtra",
        pincode="400076",
        latitude=19.1334,
        longitude=72.9133,
        aliases=["Indian Institute of Technology Bombay", "IIT Powai"],
        keywords=["iit", "campus", "powai"]
    ),
    LandmarkEntity(
        id="lm_mumbai_bkc",
        name="Bandra Kurla Complex",
        category=LandmarkCategory.COMMERCIAL,
        locality="Bandra East",
        taluka="Andheri",
        district="Mumbai Suburban",
        state="Maharashtra",
        pincode="400051",
        latitude=19.0657,
        longitude=72.8683,
        aliases=["BKC", "Bandra Kurla"],
        keywords=["financial hub", "bkc", "bandra"]
    ),
    LandmarkEntity(
        id="lm_mumbai_csmia",
        name="Chhatrapati Shivaji Maharaj International Airport",
        category=LandmarkCategory.TRANSIT,
        locality="Sahar / Santacruz",
        taluka="Andheri",
        district="Mumbai Suburban",
        state="Maharashtra",
        pincode="400099",
        latitude=19.0896,
        longitude=72.8656,
        aliases=["Mumbai Airport", "CSMIA", "Sahar Airport", "Santacruz Airport", "T2 Terminal"],
        keywords=["airport", "terminal", "flight"]
    ),

    # --- Delhi / NCR Landmarks ---
    LandmarkEntity(
        id="lm_delhi_india_gate",
        name="India Gate",
        category=LandmarkCategory.HERITAGE,
        locality="Central Secretariat",
        taluka="New Delhi",
        district="New Delhi",
        state="Delhi",
        pincode="110001",
        latitude=28.6129,
        longitude=77.2295,
        aliases=["India Gate New Delhi", "इण्डिया गेट"],
        keywords=["monument", "kartavya path", "heritage"]
    ),
    LandmarkEntity(
        id="lm_delhi_aiims",
        name="AIIMS New Delhi",
        category=LandmarkCategory.HEALTHCARE,
        locality="Ansari Nagar",
        taluka="Hauz Khas",
        district="South Delhi",
        state="Delhi",
        pincode="110029",
        latitude=28.5672,
        longitude=77.2100,
        aliases=["All India Institute of Medical Sciences", "AIIMS Hospital"],
        keywords=["hospital", "medical", "aiims"]
    ),
    LandmarkEntity(
        id="lm_delhi_igi_airport",
        name="Indira Gandhi International Airport",
        category=LandmarkCategory.TRANSIT,
        locality="Palam",
        taluka="Vasant Vihar",
        district="South West Delhi",
        state="Delhi",
        pincode="110037",
        latitude=28.5562,
        longitude=77.1000,
        aliases=["IGI Airport", "Delhi Airport", "Terminal 3 IGI"],
        keywords=["airport", "flight", "palam"]
    ),
    LandmarkEntity(
        id="lm_delhi_iit_delhi",
        name="IIT Delhi",
        category=LandmarkCategory.EDUCATION,
        locality="Hauz Khas",
        taluka="Hauz Khas",
        district="South Delhi",
        state="Delhi",
        pincode="110016",
        latitude=28.5450,
        longitude=77.1926,
        aliases=["Indian Institute of Technology Delhi"],
        keywords=["iit", "hauz khas", "engineering"]
    ),
    LandmarkEntity(
        id="lm_ncr_cyber_city",
        name="DLF Cyber City Gurugram",
        category=LandmarkCategory.TECH_PARK,
        locality="DLF Phase 2",
        taluka="Gurugram",
        district="Gurugram",
        state="Haryana",
        pincode="122002",
        latitude=28.4906,
        longitude=77.0900,
        aliases=["Cyber Hub", "DLF Cybercity", "Cyber City Gurgaon"],
        keywords=["cyber city", "cyber hub", "dlf"]
    ),

    # --- Bengaluru Landmarks ---
    LandmarkEntity(
        id="lm_blr_iisc",
        name="Indian Institute of Science Bengaluru",
        category=LandmarkCategory.EDUCATION,
        locality="Malleswaram",
        taluka="Bengaluru North",
        district="Bengaluru Urban",
        state="Karnataka",
        pincode="560012",
        latitude=13.0184,
        longitude=77.5649,
        aliases=["IISc", "Tata Institute", "IISc Bangalore"],
        keywords=["research", "malleswaram", "iisc"]
    ),
    LandmarkEntity(
        id="lm_blr_electronic_city",
        name="Electronics City Bengaluru",
        category=LandmarkCategory.TECH_PARK,
        locality="Electronic City",
        taluka="Anekal",
        district="Bengaluru Urban",
        state="Karnataka",
        pincode="560100",
        latitude=12.8452,
        longitude=77.6602,
        aliases=["Electronic City Phase 1", "Electronic City Phase 2", "E-City"],
        keywords=["tech park", "infosys", "wipro", "electronic city"]
    ),
    LandmarkEntity(
        id="lm_blr_kempegowda_airport",
        name="Kempegowda International Airport",
        category=LandmarkCategory.TRANSIT,
        locality="Devanahalli",
        taluka="Devanahalli",
        district="Bengaluru Rural",
        state="Karnataka",
        pincode="560300",
        latitude=13.1986,
        longitude=77.7066,
        aliases=["Bangalore Airport", "KIA Airport", "BLR Airport"],
        keywords=["airport", "devanahalli", "flight"]
    ),

    # --- Hyderabad Landmarks ---
    LandmarkEntity(
        id="lm_hyd_charminar",
        name="Charminar",
        category=LandmarkCategory.HERITAGE,
        locality="Old City",
        taluka="Charminar",
        district="Hyderabad",
        state="Telangana",
        pincode="500002",
        latitude=17.3616,
        longitude=78.4747,
        aliases=["Charminar Monument", "चारमीनार"],
        keywords=["monument", "heritage", "charminar"]
    ),
    LandmarkEntity(
        id="lm_hyd_hitec_city",
        name="HITEC City Hyderabad",
        category=LandmarkCategory.TECH_PARK,
        locality="Madhapur",
        taluka="Serilingampally",
        district="Hyderabad",
        state="Telangana",
        pincode="500081",
        latitude=17.4474,
        longitude=78.3762,
        aliases=["Cyberabad", "HITEC City", "Madhapur IT Hub"],
        keywords=["cyberabad", "tech park", "madhapur"]
    ),

    # --- Kolkata Landmarks ---
    LandmarkEntity(
        id="lm_ccu_victoria_memorial",
        name="Victoria Memorial Hall",
        category=LandmarkCategory.HERITAGE,
        locality="Maidan",
        taluka="Kolkata",
        district="Kolkata",
        state="West Bengal",
        pincode="700071",
        latitude=22.5448,
        longitude=88.3426,
        aliases=["Victoria Memorial", "ভিক্টোরিয়া মেমোরিয়াল"],
        keywords=["monument", "heritage", "maidan"]
    ),
    LandmarkEntity(
        id="lm_ccu_howrah_station",
        name="Howrah Railway Station",
        category=LandmarkCategory.TRANSIT,
        locality="Howrah",
        taluka="Howrah",
        district="Howrah",
        state="West Bengal",
        pincode="711101",
        latitude=22.5838,
        longitude=88.3433,
        aliases=["Howrah Junction", "Howrah Station"],
        keywords=["station", "railway", "junction"]
    ),

    # --- Chennai Landmarks ---
    LandmarkEntity(
        id="lm_maa_iit_madras",
        name="IIT Madras",
        category=LandmarkCategory.EDUCATION,
        locality="Adyar / Guindy",
        taluka="Guindy",
        district="Chennai",
        state="Tamil Nadu",
        pincode="600036",
        latitude=12.9915,
        longitude=80.2337,
        aliases=["Indian Institute of Technology Madras", "IIT Chennai"],
        keywords=["iit", "adyar", "guindy"]
    ),
    LandmarkEntity(
        id="lm_maa_central_station",
        name="Puratchi Thalaivar Dr. M.G. Ramachandran Central Railway Station",
        category=LandmarkCategory.TRANSIT,
        locality="Park Town",
        taluka="Perambur",
        district="Chennai",
        state="Tamil Nadu",
        pincode="600003",
        latitude=13.0827,
        longitude=80.2755,
        aliases=["Chennai Central", "Madras Central", "Chennai Central Station"],
        keywords=["station", "railway", "central"]
    ),
]


def get_all_landmarks() -> List[LandmarkEntity]:
    return LANDMARK_CATALOG
